### ISSUE TITLE
Ublock Origin blocks some LaunchDarkly URLs

### ISSUE THREAD

**Issue by ehuange** [launchdarkly/js-client-sdk#255] opened 2022-09-02 21:13 UTC
Similar to #62, the extension [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) blocks some requests from LaunchDarkly.

![image](https://user-images.githubusercontent.com/13304704/188236096-c29900d9-66f3-4bf4-829e-19a680b923e2.png)

**Comment by eli-darkly** [comment] 2022-09-06 18:06
We're not familiar with the user interface of this extension, so can you please interpret that screenshot for us? That is: are you saying that it is blocking _all_ LaunchDarkly domains, or only `events.launchdarkly.com`?

**Comment by eli-darkly** [comment] 2022-09-06 18:09
If it is only `events.launchdarkly.com` that's being blocked, that is known behavior; that subdomain receives analytics data from the SDK, and the extension (or rather, the EasyList site list that it's using) blocks analytics services by design. However, it would not be correct for it to be blocking the other domains, since those are not any kind of analytics service or tracker— they are for getting the values of feature flags. See: https://github.com/easylist/easylist/pull/5814

**Comment by gonzalopaniagua** [comment] 2022-09-22 12:02
Any suggestion on how to register/track users that are using Ublock or similar adblockers?

**Comment by eli-darkly** [comment] 2022-09-22 23:14
Such products are explicitly designed with a goal of making it hard to track users. Opinions may vary as to whether that's a good thing, but defeating that goal isn't something we do in our own work and it isn't something we have any expertise in. I think it would be more of a general web development question; the issue would be the same for any kind of tool that sends analytics data. Generally blockers will assume that a POST request to a third-party site (that is, a cross-origin request) that isn't a form submission must be some kind of tracking or analytics, and if they decide to block it and are able to block it, the third-party site (LD) will never know, and the JS code in the browser won't necessarily be able to distinguish it from any other kind of network failure; whether it is even reported as an error at all in JS would depend on the details of how the blocking is implemented.

**Comment by louis-launchdarkly** [comment] 2023-04-20 01:53
Closing this as there are no further comments on this issue or actions that LaunchDarkly can take.

**Closed by louis-launchdarkly** 2023-04-20 01:53 UTC

**Comment by asantos00** [comment] 2023-06-01 16:10
How can I handle these errors? I'm having a **lot** of these errors polluting my logs:

XHR error GET https://app.launchdarkly.com/sdk/evalx/<redacted>/users/<redacted>

I'm using the React Version of LaunchDarkly, but it doesn't seem to have a proper way of dealing with these errors.

**Comment by ImLunaHey** [comment] 2025-05-23 11:15
can this be reopened? if the client detects its being blocked it should stop sending events to the blocked endpoints. im seeing blocked requests to `https://events.launchdarkly.com/events/bulk` spamming network requests.
