### ISSUE TITLE
window.print() stopped working in safari after integrating js client sdk

### ISSUE THREAD

**Issue by sahilsarpal1** [launchdarkly/js-client-sdk#187] opened 2019-11-07 06:20 UTC
Print functionality stopped working just for mac safari browser.

**Description**
After integrating **launchdarkly/js-client-sdk** my print functionality stopped working. window.print() is not working.

**Steps To reproduce**
Write **window.print()** in console or in program

**Expected behavior**
Print functionality should work, 

**SDK version**
"launchdarkly-js-client-sdk": "^2.13.0",

**OS/platform**
Safari Mac

**Can anyone help me with the solution. ?**

**Comment by eli-darkly** [comment] 2019-11-07 16:13
This has been raised as an issue before (https://github.com/launchdarkly/js-client-sdk/issues/121) and is mentioned in our [troubleshooting guide](https://support.launchdarkly.com/hc/en-us/articles/360020264693). The issue is more specifically that Safari does not respect the `window.print()` command (as opposed to printing via an interactive menu command) if any JavaScript code is using an `EventSource` connection. The SDK uses `EventSource` when streaming mode is active.

As long as Safari has this bug, I can think of two possible workarounds that might be worth trying:

1. Turn off streaming (`client.setStreaming(false)`) when you are about to print, and turn it on again (`client.setStreaming(true)` to force it to be on, or `client.setStreaming()` to turn it on only if you have set a change event handler) afterward.

2. Use an EventSource polyfill such as [`js-eventsource`](https://github.com/launchdarkly/js-eventsource). However, polyfills are generally designed to only go into effect if the browser does not have its own native support for the feature, which in this case Safari does have, so I'm not entirely sure this is feasible. I also don't know whether it would actually fix the problem— it might be that Safari will refuse to print if _any_ network connection is open, not just one from its native EventSource.

I think at least the first one is worth trying, but we do need to investigate this further since it seems to be an easily reproducible problem.

**Comment by eli-darkly** [comment] 2019-11-07 16:15
This is the Safari bug report: https://bugs.webkit.org/show_bug.cgi?id=195769

**Comment by eli-darkly** [comment] 2019-11-07 17:15
Actually, sorry, I failed to notice that there is another suggested workaround: `document.execCommand('print')`.

**Comment by eli-darkly** [comment] 2019-12-10 02:02
Closing this issue since it is a duplicate of #121 and there is a documented workaround.

**Closed by eli-darkly** 2019-12-10 02:02 UTC
